name: Tests E2E
on:
  workflow_dispatch:

  push:
    branches:
      - 'master'
jobs:
  tests:
    strategy:
      matrix:
        # macos-latest platform doesn't work yet because: https://github.com/near/nearcore/issues/7235
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install modules
      run: npm install
    - name: Run E2E tests
      env:
        NEAR_ENV: ci 
        IS_GITHUB_ACTION: true
      run: npm run test-e2e